### ISSUE TITLE
Pendiente subir presentaciones 8 y 9

### ISSUE THREAD

**Issue by vcuspinera** [vcuspinera/UDG_MCD_Project_Dev_II#15]
Está pendiente que los alumnos compartan las siguientes exposiciones ya realizadas ya sea en dropbox ([en este link](https://www.dropbox.com/sh/4a8rwrbho7sleng/AACgsZnT5xhGxdaUiARnROxKa?dl=0)) o me las envíen a mi correo vcuspinera@gmail.com

Presentaciones pendientes de compartir:
- [x] Capítulo 8 - Plan de respuesta a riesgos, presentada por Mónica y Mario.
- [x] Capítulo 9 - Monitoreo y control de riesgos, presentada por Desireé y César.

**Comment by monicasoria** [comment]
> Está pendiente que los alumnos compartan las siguientes exposiciones ya realizadas ya sea en dropbox ([en este link](https://www.dropbox.com/sh/4a8rwrbho7sleng/AACgsZnT5xhGxdaUiARnROxKa?dl=0)) o me las envíen a mi correo [vcuspinera@gmail.com](mailto:vcuspinera@gmail.com)
> 
> Presentaciones pendientes de compartir:
> 
> * [x]  Capítulo 8 - Plan de respuesta a riesgos, presentada por Mónica y Mario.
> * [ ]  Capítulo 9 - Monitoreo y control de riesgos, presentada por Desireé y César.

Acabo de subir la 8 , saludos

**Comment by vcuspinera** [comment]
Gracias por subir la presentación @monicasoria! Ya también subí la presentación del capítulo 9 que mandó correo @CarolDesiree.
