### ISSUE TITLE
Material para el curso de Desarrollo de Proyectos II

### ISSUE THREAD

**Issue by vcuspinera** [vcuspinera/UDG_MCD_Project_Dev_II#2]
Como lo compartí por correo, ese mensaje tiene la finalidad de compartirles las ligas e indicaciones sobre el material del curso de Desarrollo de Proyectos II.

**DROPBOX**
El material principal será compartido a través Dropbox `UDG_MCD_Project_Dev_II Public` a la cual ya deben tener acceso con los correos que me compartieron; en caso contrario, pueden acceder a dando [click aquí.](https://www.dropbox.com/sh/k6klb0b4d6ab1ub/AAA4xuIyks58mnu3F4-BGedZa?dl=0)

En este repositorio actualmente se encuentran tres carpetas:
- **01_Admin**, donde está el temario del curso, y la información sobre los alumnos que llenamos juntos en la primer clase del miércoles 19 de enero.
- **02_Material**, los 9 capítulos del libro, así como una carpeta con el software a instalar de @Risk
- **03_Tareas**, actualmente contiene las tareas de los 9 capítulos del libro. De ser el caso, en esta carpeta se añadirían las tareas relacionadas con el material adicional que vayamos revisando en clase.

**@ RISK**
Para poder instalar el software se requiere una computadora con Windows (no funciona en sistema de Mac). 
Para la instalación es necesario ir a la carpeta de Dropbox  [02_Material/@Risk/Software](https://www.dropbox.com/sh/nx9k48m5fj6v3q9/AAAFoNLqvzsjhvdQhVYV8fMfa?dl=0). Esta carpeta contiene los siguientes dos archivos: 
- `DTSuite761-cust-Setup.exe` ejecutable para instalar el software, y
- `Palisade_Course.lic` es la licencia del software.  

Para la instalación, es necesario bajar ambos archivos en una misma carpeta, dar doble click sobre el archivo `DTSuite761-cust-Setup.exe`, y seguir los pasos de instalación. 

**PRESENTACIONES**
Las presentaciones tendrán una duración de 20 a 40 minutos, dependiendo del material de cada capítulo. Agradecería que quienes realicen las presentación **enciendan sus cámara.**

**QUIZES**
Los _quizes_ o controles de lectura se llevarán a cabo después de las exposiciones, en la última sección de cada clase. 

Esta actividad se realizará en equipo, sin embargo, __cada alumno tiene la obligación de enviar una respuesta de forma individual__.

Forma de evaluar _quizes_ (controles de lectura):
- __Evaluación sobre 100%__: Los alumnos deberán responder a esta actividad __a las 10 PM del mismo día__ para ser evaluados sobre el 100%.
- __Evaluación sobre 50%__: Los alumnos podrán entregar la actividad después de las 10 PM, con _deadline_ final __a las 11:59 PM del mismo día__, siendo acreedores a una penalización que consiste en una evaluación sobre el 50% (es decir, se asignará la mitad de la calificación obtenida). 
- __Evaluación igual a 0%__: En caso de no responder en este periodo, la calificación será cero.

**TAREAS**  
Habrá dos tipos de tareas:

1) Tareas del libro de texto "Libro PMI-RMP Exam Preparation" las cuales se encuentran en dropbox ([dar click aquí](https://www.dropbox.com/sh/tv3uqltxs911tph/AACrsVcEWmiDh_gj3jogdQQia?dl=0)).

2) Tareas de actividades adicionales, las cuales se les hará saber durante la clase y se publicarán como [Issue en el repositorio de GitHub de la materia (UDG_MCD_Project_Dev_II)](https://github.com/vcuspinera/UDG_MCD_Project_Dev_II/issues). 

**GITHUB**
Para quienes aún no tienen abierta una cuenta de GitHub, me gustaría que fueran abriéndola, lo cual se puede hacer en la siguiente la página: [https://github.com > Sign up](https://github.com).  En caso que ya tengan su cuenta de GitHub, favor de compartirme su nombre de usuario. 

Además, se ha creado el repositorio [`UDG_MCD_Project_Dev_II`](https://github.com/vcuspinera/UDG_MCD_Project_Dev_II) para el curso, donde estaremos compartiendo material adicional, y el cual utilizaremos para hacer algunos ejercicios.

**SLACK**
Por último, les comento que creé un espacio de comunicación en [Slack](https://slack.com) para el curso con el nombre `UDG MCD Desarrollo de Proyectos II`, el cual me gustaría que utilizaran para practicar como usar esta herramienta. Ya les debió haber llegado un correo para que puedan accesar a este espacio; en caso contrario, favor de enviarme un correo a vcuspinera@gmail.com

En este espacio encontrarán los siguientes canales:
- **canal_principal**, el cual es el canal principal de comunicación en este espacio,
- **tareas**, donde podrán discutir y compartir sus dudas sobre las tareas 
- **preguntas**, donde pueden realizar preguntas, contestarlas y apoyarse mutuamente
- **tools**, en caso que quieran compartir alguna herramienta, programa, curso, etc. de ciencias de datos que crean relevante
- **a-risk**, para dudas, preguntas y comentarios relacionados con el software de @RISK
- **random**, para compartir material distinto al del curso como ideas personales, memes, videos, chistes, gifs
- **equipo_N**, donde ’N’ es su número de equipo, el cual es un canal privado para que trabajen en equipo.

Quedo pendiente por cualquier duda, aclaración o comentario.

Saludos,
Víctor Cuspinera

**Comment by oliviamcd** [comment]
Hola @vcuspinera 
 ¿Me puedes asignar como colaboradora por favor? Gracias.

**Comment by vcuspinera** [comment]
Hola @oliviamcd,
Ya te asigné como colaboradora, te debió haber llegado un correo a tu cuenta asociada al usuario de github, pero si no te ha llegado deberías poder accesar a través del siguiente link: https://github.com/vcuspinera/UDG_MCD_Project_Dev_II/invitations 
Saludos
