### ISSUE TITLE
Link para aplicar a posiciones en las Naciones Unidas

### ISSUE THREAD

**Issue by AndresPitta** [vcuspinera/UDG_MCD_Project_Dev_II#39]
Estimadas y estimados,

Acá puede encontrar algunos links útiles para aplicar a posiciones en las Naciones Unidas:

- [Inspira](https://inspira.un.org/psp/PUNA1J/?cmd=login&languageCd=ENG): Esta es la página principal de reclutamiento. Tienen que loguearse y buscar posiciones.
- [UN Volunteers](https://www.unv.org/es): Esta es la página de voluntariados. Son contratos más cortos y se pueden hacer en cualquier parte del mundo y te dan dinero de realocación.
- [Young Professionals Program](https://careers.un.org/lbw/home.aspx?viewtype=nce): Esto es como una evaluación para jóvenes menores de 32 años de países subrepresentados en la ONU. Es como un programa de semilleros. Colombia ni México, por ejemplo, están subrepresentados este año, pero eso va cambiando cada año.

Cualquier comentario, déjenmelo saber,
Andrés!

**Comment by vcuspinera** [comment]
Gracias por compartir esta información con los estudiantes @AndresPitta!

**Comment by vcuspinera** [comment]
Reabro el Issue para quien esté interesado en esta información compartida por el Mtro Andrés Pitta acerca de la aplicación a posiciones para la ONU.

**Comment by vcuspinera** [comment]
Gracias por el apoyo @AndresPitta!
