### ISSUE TITLE
Problemas para hacer push

### ISSUE THREAD

**Issue by D4NT3002** [vcuspinera/UDG_MCD_Project_Dev_II#64]
Hola profesor, espero que se encuentre bien, le comparto que ayer terminé mi proyecto EDA y tuve un ![error al cargar](https://user-images.githubusercontent.com/94881702/226404171-711a415f-d701-42c9-a48e-a9d7d8ec05c9.jpg) , derivado de lo que menciona el error, intenté resolverlo, pero a pesar de sacar los archivos pesados, no me dejó hacer el push, similarmente el archivo python no se alcanza a visualizar como debe, integré imágenes en representación de lo que se ve (quedan cortas). En fin, no se hizo el push con todos los cambios y creo que ya tengo conflictos de versiones entre git y git local. Subí los archivos de manera manual.

**Comment by vcuspinera** [comment]
De acuerdo Gabriel, al parecer el error tiene que ver con el tamaño de los archivos. Si quieres nos coordinamos para hacer una videollamada y tratar de resolver el caso. Si quieres que nos reunamos a mi se me facilita por las tardes después de las 6pm, me avisas por correo qué día y hora te queda bien.
