### ISSUE TITLE
¡Bienvenida al curso, ciclo escolar 2023-B!

### ISSUE THREAD

**Issue by vcuspinera** [vcuspinera/UDG_MCD_Project_Dev_II#73]
Hola, alumnos:
Antes de iniciar la clase, quiero darles la bienvenida al curso de **Desarrollo de Proyectos I** de la Maestría en Ciencia de los Datos del **ciclo escolar 2023-B (semestre de otoño)**. Espero que el material del curso les sirva para sus futuros proyectos profesionales, académicos y personales.

Saludos,
Víctor Cuspinera

**Comment by disita** [comment]
Hola!

**Comment by vcuspinera** [comment]
Se cierra la bienvenida al curso después de la primera semana.
